# Generated by Django 5.1.6 on 2025-02-28 22:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('details', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Detalhes do Processamento')),
                ('process_status', models.CharField(choices=[('1', 'aguardando processamento'), ('2', 'em fila para processamento'), ('3', 'processando'), ('4', 'processado com sucesso'), ('5', 'erro ao processar')], default='aguardando processamento', max_length=30, verbose_name='Status do Processamento')),
                ('start_processing', models.DateTimeField(blank=True, null=True, verbose_name='Incio do Processamento')),
                ('ending_processing', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Processamento')),
            ],
        ),
    ]
