# Generated by Django 5.1.6 on 2025-03-01 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('process_status', models.CharField(choices=[('1', 'aguardando processamento'), ('2', 'em fila para processamento'), ('3', 'processando'), ('4', 'processado com sucesso'), ('5', 'erro ao processar')], default='aguardando processamento', max_length=30, verbose_name='Status do Processamento')),
                ('start_processing', models.DateTimeField(blank=True, null=True, verbose_name='Incio do Processamento')),
                ('ending_processing', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Processamento')),
            ],
        ),
        migrations.DeleteModel(
            name='CoreProcess',
        ),
    ]
