# Generated by Django 5.1.6 on 2025-03-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_core_delete_coreprocess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Core',
        ),
    ]
