# Generated by Django 5.1.10 on 2025-09-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('BRL', 'Brazilian Real')], default='USD', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('PT', 'Portuguese')], default='EN', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=[('UTC-11', '(GMT-11:00) International Date Line West'), ('UTC+0', '(GMT+0:00) Coordinated Universal Time'), ('UTC+3', '(GMT+3:00) Moscow, St. Petersburg')], default='UTC+0', max_length=20),
        ),
    ]
