# Generated by Django 5.1.10 on 2025-09-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_currency_user_language_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('BR', 'Brazil'), ('US', 'United States'), ('CA', 'Canada')], default='BR', max_length=2, verbose_name='País'),
        ),
    ]
