# Generated by Django 5.1.10 on 2025-09-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='Endereço completo do usuário (rua, número, complemento).', max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, help_text='Nome da empresa ou instituição do usuário.', max_length=100, null=True, verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Número de telefone do usuário.', max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, help_text='Estado ou província do usuário.', max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Código postal do usuário.', max_length=20, null=True, verbose_name='CEP'),
        ),
    ]
